# Generated by Django 4.2.4 on 2023-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/photos')),
                ('image_center', models.ImageField(blank=True, null=True, upload_to='blog/photos')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='blog/photos')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='blog/photos')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vip_content', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('github_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
